import { type LucideIcon, Code, Wand2, ArrowRightLeft, Link as LinkIcon, Hash, CaseUpper, FileType, Baseline, Lock, Shield, Key, Braces, Binary, Text, Fingerprint, Unplug, GitCompareArrows, FileJson, FileCode, FileImage, Minimize, Shrink, Crop, ScanEye, ScanSearch, ImageUp, ImageDown, Palette, Pipette, Layers, Clock, Globe, Calendar, SpellCheck, ShieldCheck, ShieldAlert } from 'lucide-react';

export type Tool = {
  id: string;
  name: string;
  description: string;
  category: keyof typeof TOOL_CATEGORIES;
  icon: LucideIcon;
};

export const TOOL_CATEGORIES = {
  'code': {
    name: 'Code Tools',
    icon: Code,
  },
  'encoding': {
    name: 'Encoding & Decoding',
    icon: ArrowRightLeft,
  },
  'security': {
    name: 'Hashing & Security',
    icon: Lock,
  },
  'text': {
    name: 'Text & Data',
    icon: Text,
  },
  'regex-string': {
    name: 'Regex & String',
    icon: SpellCheck,
  },
  'conversion': {
    name: 'Data Conversion',
    icon: GitCompareArrows,
  },
  'image': {
    name: 'Image Tools',
    icon: FileImage,
  },
  'color': {
    name: 'Color & Design',
    icon: Palette,
  },
  'time': {
    name: 'Time & Date Tools',
    icon: Clock,
  },
};

export const TOOLS_LIST: Tool[] = [
  {
    id: 'js-minifier',
    name: 'JS Minifier',
    description: 'Minify JavaScript code to reduce file size.',
    category: 'code',
    icon: FileType,
  },
  {
    id: 'js-beautifier',
    name: 'JS Beautifier',
    description: 'Format and beautify JavaScript code for readability.',
    category: 'code',
    icon: Wand2,
  },
  {
    id: 'js-obfuscator',
    name: 'JS Obfuscator',
    description: 'Make JavaScript code difficult to understand.',
    category: 'code',
    icon: Shield,
  },
  {
    id: 'es6-to-es5-converter',
    name: 'ES6 to ES5 Converter',
    description: 'Convert modern JavaScript to a legacy-compatible version.',
    category: 'code',
    icon: Unplug,
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier',
    description: 'Minify CSS code to reduce file size.',
    category: 'code',
    icon: FileType,
  },
  {
    id: 'css-beautifier',
    name: 'CSS Beautifier',
    description: 'Format and beautify CSS code for readability.',
    category: 'code',
    icon: Wand2,
  },
  {
    id: 'html-minifier',
    name: 'HTML Minifier',
    description: 'Minify HTML code to reduce file size.',
    category: 'code',
    icon: FileType,
  },
  {
    id: 'html-beautifier',
    name: 'HTML Beautifier',
    description: 'Format and beautify HTML code for readability.',
    category: 'code',
    icon: Wand2,
  },
  {
    id: 'base64-encoder-decoder',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode to and decode from Base64.',
    category: 'encoding',
    icon: ArrowRightLeft,
  },
  {
    id: 'url-encoder-decoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode or decode strings for use in URLs.',
    category: 'encoding',
    icon: LinkIcon,
  },
  {
    id: 'html-entities-encoder-decoder',
    name: 'HTML Entities Encoder/Decoder',
    description: 'Encode or decode HTML entities.',
    category: 'encoding',
    icon: Braces,
  },
  {
    id: 'unicode-converter',
    name: 'Unicode Converter',
    description: 'Convert text to and from Unicode codes.',
    category: 'encoding',
    icon: Binary,
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode a JSON Web Token to view its payload.',
    category: 'encoding',
    icon: Key,
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate SHA-1, SHA-256, and SHA-512 hashes.',
    category: 'security',
    icon: Hash,
  },
  {
    id: 'md5-hash-generator',
    name: 'MD5 Hash Generator',
    description: 'Generate an MD5 hash of a given text.',
    category: 'security',
    icon: Hash,
  },
  {
    id: 'hmac-generator',
    name: 'HMAC Generator',
    description: 'Generate a Hash-based Message Authentication Code.',
    category: 'security',
    icon: Fingerprint,
  },
  {
    id: 'bcrypt-hasher',
    name: 'Password Hashing (bcrypt)',
    description: 'Securely hash passwords using the bcrypt algorithm.',
    category: 'security',
    icon: ShieldCheck,
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text to different cases (uppercase, lowercase, etc.).',
    category: 'text',
    icon: CaseUpper,
  },
  {
    id: 'word-counter',
    name: 'Word & Character Counter',
    description: 'Count words and characters in a block of text.',
    category: 'text',
    icon: Text,
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions.',
    category: 'regex-string',
    icon: Wand2,
  },
  {
    id: 'string-escaper',
    name: 'String Escaper',
    description: 'Escape special characters in a string.',
    category: 'regex-string',
    icon: ArrowRightLeft,
  },
  {
    id: 'string-unescaper',
    name: 'String Unescaper',
    description: 'Unescape special characters in a string.',
    category: 'regex-string',
    icon: ArrowRightLeft,
  },
  {
    id: 'slug-generator',
    name: 'Slug Generator',
    description: 'Create a URL-friendly slug from a string.',
    category: 'regex-string',
    icon: LinkIcon,
  },
  {
    id: 'random-string-generator',
    name: 'Random String Generator',
    description: 'Generate a random string of a specified length.',
    category: 'regex-string',
    icon: Hash,
  },
  {
    id: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text.',
    category: 'regex-string',
    icon: Baseline,
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    description: 'Convert CSV data to JSON format.',
    category: 'conversion',
    icon: FileJson,
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV',
    description: 'Convert JSON data to CSV format.',
    category: 'conversion',
    icon: FileCode,
  },
  {
    id: 'xml-to-json',
    name: 'XML to JSON',
    description: 'Convert XML data to JSON format.',
    category: 'conversion',
    icon: FileJson,
  },
  {
    id: 'json-to-xml',
    name: 'JSON to XML',
    description: 'Convert JSON data to XML format.',
    category: 'conversion',
    icon: FileCode,
  },
  {
    id: 'yaml-to-json',
    name: 'YAML to JSON',
    description: 'Convert YAML data to JSON format.',
    category: 'conversion',
    icon: FileJson,
  },
  {
    id: 'json-to-yaml',
    name: 'JSON to YAML',
    description: 'Convert JSON data to YAML format.',
    category: 'conversion',
    icon: FileCode,
  },
  {
    id: 'markdown-to-html',
    name: 'Markdown to HTML',
    description: 'Convert Markdown text to HTML.',
    category: 'conversion',
    icon: FileCode,
  },
  {
    id: 'html-to-markdown',
    name: 'HTML to Markdown',
    description: 'Convert HTML to Markdown text.',
    category: 'conversion',
    icon: FileCode,
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress JPG, PNG, and WebP images to reduce file size.',
    category: 'image',
    icon: Minimize,
  },
  {
    id: 'image-converter',
    name: 'Image Format Converter',
    description: 'Convert images between formats like JPG, PNG, and WebP.',
    category: 'image',
    icon: ArrowRightLeft,
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize images to specific dimensions.',
    category: 'image',
    icon: Shrink,
  },
  {
    id: 'image-cropper',
    name: 'Image Cropper',
    description: 'Crop images to a specific area.',
    category: 'image',
    icon: Crop,
  },
  {
    id: 'image-to-base64',
    name: 'Image to Base64',
    description: 'Convert an image to a Base64 string.',
    category: 'image',
    icon: ImageUp,
  },
  {
    id: 'base64-to-image',
    name: 'Base64 to Image',
    description: 'Convert a Base64 string back to an image.',
    category: 'image',
    icon: ImageDown,
  },
  {
    id: 'image-metadata-viewer',
    name: 'Image Metadata Viewer',
    description: 'View EXIF and other metadata from an image.',
    category: 'image',
    icon: ScanEye,
  },
  {
    id: 'image-metadata-remover',
    name: 'Image Metadata Remover',
    description: 'Remove all metadata from an image.',
    category: 'image',
    icon: ScanSearch,
  },
  {
    id: 'color-picker',
    name: 'Color Picker',
    description: 'Select a color and get its value in different formats.',
    category: 'color',
    icon: Pipette,
  },
  {
    id: 'color-palette-generator',
    name: 'Color Palette Generator',
    description: 'Generate color palettes from a base color.',
    category: 'color',
    icon: Palette,
  },
  {
    id: 'gradient-generator',
    name: 'Gradient Generator',
    description: 'Create CSS gradients with a visual editor.',
    category: 'color',
    icon: Layers,
  },
  {
    id: 'hex-to-rgb-converter',
    name: 'HEX to RGB Converter',
    description: 'Convert HEX color codes to RGB values.',
    category: 'color',
    icon: ArrowRightLeft,
  },
  {
    id: 'rgb-to-hex-converter',
    name: 'RGB to HEX Converter',
    description: 'Convert RGB color values to HEX codes.',
    category: 'color',
    icon: ArrowRightLeft,
  },
  {
    id: 'hsl-to-hex-converter',
    name: 'HSL to HEX Converter',
    description: 'Convert HSL color values to HEX codes.',
    category: 'color',
    icon: ArrowRightLeft,
  },
  {
    id: 'image-color-extractor',
    name: 'Image Color Extractor',
    description: 'Extract the most prominent colors from an image.',
    category: 'color',
    icon: Pipette,
  },
  {
    id: 'unix-timestamp-converter',
    name: 'Unix Timestamp Converter',
    description: 'Convert Unix timestamps to human-readable dates.',
    category: 'time',
    icon: Clock,
  },
  {
    id: 'timezone-converter',
    name: 'Timezone Converter',
    description: 'Convert dates and times between different timezones.',
    category: 'time',
    icon: Globe,
  },
  {
    id: 'date-calculator',
    name: 'Date Calculator',
    description: 'Add or subtract days, weeks, months, and years from a date.',
    category: 'time',
    icon: Calendar,
  },
];

export const TOOLS_MAP = new Map(TOOLS_LIST.map((tool) => [tool.id, tool]));
